package com.example.ecommerce.exception;

public enum ResponseMessage {
    SUCCESS,
    ACCOUNT_ACTIVATION_SUCCESSFUL,
    USER_REGISTRATION_SUCCESSFUL,

    PROFILE_UPDATE_SUCCESSFUL,
    NOTIFICATION_SENT_SUCCESSFULLY
}
